kmap('n', 'ｈ', 'h')
kmap('n', 'ｊ', 'j')
kmap('n', 'ｋ', 'k')
kmap('n', 'ｌ', 'l')
kmap('n', 'ｒ', 'r')
kmap('n', 'あ', 'a')
kmap('n', 'い', 'i')
kmap('n', 'う', 'u')
kmap('n', 'お', 'o')
kmap('n', 'っｄ', 'dd')
kmap('n', 'っｙ', 'yy')
kmap('n', 'し”', 'ci"')
kmap('n', 'し’', 'ci\'')

